SetPrivateProfileString('Keymap Action','Special Abilities','102')
SetPrivateProfileString('Keymap Action','Cast Spell','115')
SetPrivateProfileString('Keymap Action','Use Item','100')
SetPrivateProfileString('Keymap Action','Stealth','120')
SetPrivateProfileString('Keymap Action','Dialog','103')
SetPrivateProfileString('Keymap Action','Trap Detection','118')
SetPrivateProfileString('Keymap Action','Thieving','122')
SetPrivateProfileString('Keymap Page','Character Stats','99')
SetPrivateProfileString('Keymap Page','Return To Game','0')
SetPrivateProfileString('MOVIES','LOGO','1')
SetPrivateProfileString('MOVIES','TIME','1')
SetPrivateProfileString('MOVIES','CREDITS','1')
SetPrivateProfileString('MOVIES','SIGIL','1')
SetPrivateProfileString('MOVIES','OPENING','1')
SetPrivateProfileString('MOVIES','SS_MSLAB','1')
SetPrivateProfileString('Program Options','Path Search Nodes','32000')
SetPrivateProfileString('Program Options','Tooltips','0')
SetPrivateProfileString('Program Options','Maximum Frame Rate','40')
SetPrivateProfileString('Program Options','Display Subtitles','1')
SetPrivateProfileString('Program Options','Volume Voices','84')
SetPrivateProfileString('Program Options','Volume Movie','64')
SetPrivateProfileString('Program Options','Volume SFX','66')
SetPrivateProfileString('Program Options','3D Acceleration','1')
SetPrivateProfileString('Program Options','Volume Ambients','23')
SetPrivateProfileString('Program Options','Disable Cosmetic Attacks','0')
SetPrivateProfileString('Program Options','Never Show Nuisance PST','1')
SetPrivateProfileString('Program Options','Brightness Correction','2')
SetPrivateProfileString('Program Options','Sprite Mirror','1')
SetPrivateProfileString('Program Options','Translucent Shadows','1')
SetPrivateProfileString('Program Options','Drop Capitals','1')
SetPrivateProfileString('Program Options','Font Name','')
SetPrivateProfileString('Program Options','Volume Music','23')
SetPrivateProfileString('Program Options','Use Touch Actionbar','0')
SetPrivateProfileString('Window','Maximized','0')
SetPrivateProfileString('Window','Full Screen','1')
SetPrivateProfileString('Keymap Character Selection','Multiselect all','96')
SetPrivateProfileString('Game Options','Ranged Weapon Switching','0')
SetPrivateProfileString('Game Options','Suppress Extra Difficulty Damage','0')
SetPrivateProfileString('Game Options','Critical Hit Screen Shake','1')
SetPrivateProfileString('Game Options','CombatY','0')
SetPrivateProfileString('Game Options','Combat UI','0')
SetPrivateProfileString('Game Options','No Difficulty Based XP Bonus','1')
SetPrivateProfileString('Game Options','Always Run','1')
SetPrivateProfileString('Game Options','Message Box Top','175')
SetPrivateProfileString('Game Options','Show Actionbar Help','0')
SetPrivateProfileString('Game Options','Duplicate Floating Text','1')
SetPrivateProfileString('Game Options','Filter Games','1')
SetPrivateProfileString('Game Options','Last Save PST','000000012-Mot')
SetPrivateProfileString('Game Options','HP Over Head','0')
SetPrivateProfileString('Game Options','Footsteps','1')
SetPrivateProfileString('Game Options','Show Learnable Spells','1')
SetPrivateProfileString('Game Options','Locator Feedback Level','3')
SetPrivateProfileString('Game Options','Auto Pause State','1169')
SetPrivateProfileString('Game Options','Smooth Area Transitions','1')
SetPrivateProfileString('Game Options','Maximum HP','1')
SetPrivateProfileString('Game Options','Extra Feedback','0')
SetPrivateProfileString('Game Options','Tiles Precache Percent','100')
SetPrivateProfileString('Game Options','Terrain Hugging','0')
SetPrivateProfileString('Game Options','CombatX','0')
SetPrivateProfileString('Game Options','Nightmare Bonus Gold','0')
SetPrivateProfileString('Game Options','Heal Party on Rest','0')
SetPrivateProfileString('Game Options','Health Bar Settings','0')
SetPrivateProfileString('Game Options','Render Actions','0')
SetPrivateProfileString('Game Options','Nightmare Bonus XP','0')
SetPrivateProfileString('Game Options','Journal Popups','1')
SetPrivateProfileString('Game Options','Command Sounds Frequency','2')
SetPrivateProfileString('Game Options','CombatH','94')
SetPrivateProfileString('Game Options','Show Enemy Health Status','1')
SetPrivateProfileString('Game Options','Difficulty Level','3')
SetPrivateProfileString('Game Options','3E Thief Sneak Attack','0')
SetPrivateProfileString('Game Options','Cleric Ranger Spells','1')
SetPrivateProfileString('Game Options','Pausing Map','0')
SetPrivateProfileString('Game Options','Color Circles','0')
SetPrivateProfileString('Game Options','Attack Sounds','1')
SetPrivateProfileString('Game Options','Memory Level','1')
SetPrivateProfileString('Game Options','GUI Feedback Level','5')
SetPrivateProfileString('Game Options','Confirm Dialog','0')
SetPrivateProfileString('Game Options','Show Character HP','1')
SetPrivateProfileString('Game Options','Always Dither','1')
SetPrivateProfileString('Game Options','Show Message Box Hint','0')
SetPrivateProfileString('Game Options','Keyboard Scroll Speed','37')
SetPrivateProfileString('Game Options','Auto Pause Center','1')
SetPrivateProfileString('Game Options','Subtitles','1')
SetPrivateProfileString('Game Options','Environmental Audio','1')
SetPrivateProfileString('Game Options','Infravision','0')
SetPrivateProfileString('Game Options','Effect Text Level','63')
SetPrivateProfileString('Game Options','Classic Selection Circles','0')
SetPrivateProfileString('Game Options','Bored Timeout','3000')
SetPrivateProfileString('Game Options','Mouse Scroll Speed','56')
SetPrivateProfileString('Game Options','Tutorial State','1')
SetPrivateProfileString('Game Options','Hotkeys On Tooltips','1')
SetPrivateProfileString('Game Options','Quick Item Mapping','1')
SetPrivateProfileString('Game Options','Selection Sounds Frequency','3')
SetPrivateProfileString('Game Options','Over Confirm Everything','1')
SetPrivateProfileString('Game Options','Render Explored Map','0')
SetPrivateProfileString('Game Options','All Learn Spell Info','1')
SetPrivateProfileString('Game Options','Area Effects Density','100')
SetPrivateProfileString('Game Options','Weather','1')
SetPrivateProfileString('Game Options','Render Travel Regions','0')
SetPrivateProfileString('Language','Text','en_US')
SetPrivateProfileString('Fonts','zh_CN','SIMSUN')
SetPrivateProfileString('Fonts','uk_UA','PERMIAN')
SetPrivateProfileString('Fonts','ko_KR','NANUM')
SetPrivateProfileString('Fonts','Zoom','114')
SetPrivateProfileString('Fonts','ru_RU','PTSERIF')
SetPrivateProfileString('Fonts','ja_JP','MEIRYO')
SetPrivateProfileString('Graphics','vendor','NVIDIA Corporation')
SetPrivateProfileString('Graphics','Use Sprite Outlines','1')
SetPrivateProfileString('Graphics','Use Linear Scaling','1')
SetPrivateProfileString('Graphics','Use Double Size Cursors','0')
SetPrivateProfileString('Graphics','Zoom Lock','0')
SetPrivateProfileString('Graphics','renderer','GeForce GT 430/PCIe/SSE2')
SetPrivateProfileString('Graphics','Greyscale On Pause','1')
SetPrivateProfileString('Graphics','Use Character Highlights','1')
SetPrivateProfileString('Graphics','Gameworld Scaling','1')
SetPrivateProfileString('Graphics','Scale UI','1')
SetPrivateProfileString('Graphics','Show Black Space','0')
SetPrivateProfileString('Graphics','Gamma','110')
SetPrivateProfileString('Graphics','Backend','0')
SetPrivateProfileString('Graphics','Hardware Mouse Cursor','1')
SetPrivateProfileString('Graphics','version','OpenGL version 4.5.0 NVIDIA 378.78 - build XXXX')
SetPrivateProfileString('Multiplayer','Disable Banters','1')
SetPrivateProfileString('Multiplayer','Enable Chat Menu','1')
SetPrivateProfileString('Keymap Miscellaneous','Location','0')
SetPrivateProfileString('Keymap Miscellaneous','Center Character','0')
